### ISSUE TITLE
Error: Cannot find module 'depd'

### ISSUE THREAD

**Issue by MakeMoneyMan** [wangxiao/romantic#1]
D:\otherWork\七夕交友>lean up
提示：键入 rs 命令并回车来强制重启本进程
提示：使用 http://localhost:3001 测试 Cloud 函数

> node-js-getting-started@1.0.0 start D:\otherWork\七夕交友
> node server.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'depd'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\otherWork\七夕交友\node_modules\leanengine\node_modules\body-parser\index.js:11:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! node-js-getting-started@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-js-getting-started@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the node-js-getting-started package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-js-getting-started
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-js-getting-started
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\otherWork\七夕交友\npm-debug.log

**Comment by wangxiao** [comment]
maybe need `npm install depd`

**Comment by dajige99** [comment]
全国24小时空降平台_同城上门约啪 - 同城约炮交友 - 免费同城啪啪夜约 - 听话水 - 液体快乐丸 - 迷药网络销售
<a href="https://yue4.com"  target="_blank">👉点击开约【yue4.com】👈</a>
♥♥♥♥♥♥♥♥♥♥♥♥♥♥
<a href="https://yue4.com"  target="_blank">👉点击开约【yue4.com】👈</a>
♥♥♥♥♥♥♥♥♥♥♥♥♥♥

网址打不开？？？

1.请切换网络 WIFI/4G/5G 或者使用 科学上网工具（VPN）

2.请拷贝完整地址到浏览器访问， 有前缀 https://

3.请苹果手机使用 Safari 浏览器、安卓手机使用 Chrome 浏览器，夸克浏览器。

请把网址分享给身边有需要的人 ，您的转发、分享是我们前进的动力～


在这个多姿多彩的世界里，女性如同繁星般璀璨，每个女人都有着自己独特的魅力，让人难以琢磨透。

随着社会的不断进步，女性的观念也逐渐开放，越来越多的女性不再甘于寂寞，敢于追求属于自己的幸福。

上个月，项目的忙碌让我有些心烦意乱，终于闲下来的时候，一种无聊的情绪袭上心头。

孤独的夜晚，我不禁开始东想西想，就在这个时候，无意中上了一个网站。




惊讶地发现那里都是一些寂寞的女性，她们对于出轨有些意向，让我好奇心燃起，欲望也蠢蠢欲动。

我随意开了一个高级VIP会员，那里迅速给我介绍了一个白领女性。和她聊天时，我发现她非常开放，对什么都无所谓，似乎容易冲动而且善于沟通。

于是我直接问她对网上交友上床的看法，她干脆地回答说喜欢凭感觉行事。或许她也是感到空虚，她默认了我的意图，我们见面后发生了一段让人情理之中的故事。

她是一位美丽的女性，皮肤略微偏黑，但散发着健康的美。那个周六晚上，我约她下班后共进晚餐，我们中间喝了些酒，然后来到了一家酒店。




对于我们而言，见面已经注定了什么，她的表现非常随性，让我觉得这对她来说似乎是再普通不过的事情。

我们毫不拖泥带水地去开房，我搂着她的腰，她的身材无可挑剔，她的经验也非常丰富，和我配合得天衣无缝。

我用行动征服了她，她赞扬我很棒，满足了我的虚荣心。在我们的配合下，彼此都得到了满足，达到了双赢的境地。

随后，我们再没有联系，那样的女人只适合一夜情，我对她的兴趣也就到此为止。




又一次上网时，系统推荐了另一个女性，让我有些心动，继续勾起我的不安感。

第二个女人是一位少妇，她的丈夫经常出差，是那种隐约有点闷骚、寂寞的女人。对于网上的色情话题她并不直接回应，但她心里并不排斥。

每个女人的个性都不同，有些敞开心扉，而有些则总是装出不在意的样子，却暗自心动。但这并不妨碍我们的交往。

她通过侧面的暗示向我表达内心的寂寞，有时候她会表示晚上失眠，想找个人聊聊天。我明白她的真实想法，她虽然不直接表露，但需要我的引导。

之后，我们的语言更加暧昧，她嘴上叫我别这样，但并没有阻止我继续。她的心思我都懂，于是我们很快见了一面。她主动约我，但她带着她的女儿一起来。




我明白她的谨慎，她有点小聪明，这样的约会不尴尬，也能考察我对她的感觉，真是聪明之举。

第一次见面我们只是简单吃了个饭，什么都没发生。她对我印象很好，第二次则是我约她。之后我们终于发生了关系，她心里想搞事，但做得比较谨慎，不留痕迹。

或许对她来说，这只是暂时的寄托，她不愿让感情变得过于复杂。我心里一片欲望，她成为我渴望的对象，开心成了最重要的事情。

之后我们还在网上聊过，但她的态度逐渐不如之前热情了，慢慢地也不怎么理我了。我也并非傻子，自然能明白她的意思，懂得自己该收手，识相地没有再联系。

社会虽然开放，女性的观念也在逐渐改变，但我们也要学会适时地放下，不要太过贪恋。
