### ISSUE TITLE
能否告知一下build此项目的node版本，谢谢！

### ISSUE THREAD

**Issue by xiongchengqing** [wangxiao/romantic#2]
能否告知一下build此项目的node版本，谢谢！

gulp build 时总会报错，怀疑是用了不合适的node版本。我的node版本 `v6.2.2`

![image](https://cloud.githubusercontent.com/assets/1636616/17077786/444d891e-5110-11e6-9a76-23779d1254c6.png)

**Comment by wangxiao** [comment]
你好，版本是 nodejs 4.x

**Comment by wangxiao** [comment]
nodejs 6.x 应该也是支持的，你需要将相关库升级到支持 6.x 的版本。
